"""Obsidian Canvas (`.canvas`) generator for workspace maps.

Each workspace gets a ``Workspace Map.canvas`` that visualises the
workspace's structure: hot cache, index, log, and the N most-recent
session notes. The capture pipeline regenerates this after every
successful capture so it never goes stale.

Canvas file format: JSON with two top-level arrays — ``nodes`` and
``edges``. Each node has ``id``, ``type`` (``"file"``, ``"text"``,
``"link"``, ``"group"``), and positional ``x``/``y``/``width``/``height``.
Edges have ``id``, ``fromNode``, ``toNode``. We stick to file + text
nodes; Obsidian renders everything.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path

from contextvault.vault import Vault

__all__ = ["build_workspace_canvas", "regenerate_workspace_canvas", "render_canvas_json"]


_SESSION_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})")


def regenerate_workspace_canvas(
    vault: Vault, workspace: str, *, max_sessions: int = 8
) -> str:
    """Rewrite ``workspaces/<ws>/Workspace Map.canvas`` and return the rel path."""
    payload = build_workspace_canvas(vault, workspace, max_sessions=max_sessions)
    rel = f"workspaces/{workspace}/Workspace Map.canvas"
    vault.write(rel, render_canvas_json(payload))
    return rel


def build_workspace_canvas(
    vault: Vault, workspace: str, *, max_sessions: int = 8
) -> dict[str, object]:
    """Compose the canvas payload as a dict (caller renders to JSON)."""
    ws_root = f"workspaces/{workspace}"
    if not (vault.root / ws_root).is_dir():
        return {"nodes": [], "edges": []}

    nodes: list[dict[str, object]] = []
    edges: list[dict[str, object]] = []

    # Header text card at the top.
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    nodes.append(
        {
            "id": "header",
            "type": "text",
            "text": (
                f"# Workspace `{workspace}`\n\n"
                f"_Auto-generated by ContextVault on {now}_"
            ),
            "x": 0,
            "y": 0,
            "width": 600,
            "height": 120,
        }
    )

    # Pillar files: hot, index, log
    pillars = [
        ("hot", f"{ws_root}/hot.md", "Hot cache"),
        ("index", f"{ws_root}/index.md", "Index"),
        ("log", f"{ws_root}/log.md", "Log"),
    ]
    pillar_y = 180
    for i, (node_id, rel, label) in enumerate(pillars):
        if not vault.exists(rel):
            continue
        nodes.append(
            {
                "id": node_id,
                "type": "file",
                "file": rel,
                "x": i * 220,
                "y": pillar_y,
                "width": 200,
                "height": 100,
                "label": label,
            }
        )
        edges.append(
            {"id": f"e-header-{node_id}", "fromNode": "header", "toNode": node_id}
        )

    # Session column on the right (most recent first).
    sessions_dir = vault.root / ws_root / "sessions"
    if sessions_dir.is_dir():
        session_paths = sorted(
            sessions_dir.glob("*.md"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )[:max_sessions]
        session_x = 700
        for i, sp in enumerate(session_paths):
            rel = sp.relative_to(vault.root).as_posix()
            node_id = f"session-{i}"
            label = _session_label(rel)
            nodes.append(
                {
                    "id": node_id,
                    "type": "file",
                    "file": rel,
                    "x": session_x,
                    "y": i * 130,
                    "width": 320,
                    "height": 110,
                    "label": label,
                }
            )
            edges.append(
                {
                    "id": f"e-header-{node_id}",
                    "fromNode": "header",
                    "toNode": node_id,
                }
            )

    return {"nodes": nodes, "edges": edges}


def render_canvas_json(payload: dict[str, object]) -> str:
    """Serialize a canvas payload as the JSON Obsidian expects."""
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _session_label(rel_path: str) -> str:
    """Best-effort short label for a session file (date + short-id)."""
    name = Path(rel_path).stem
    match = _SESSION_DATE_RE.match(name)
    if match:
        return name
    return name[:32]
